//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpInfo()
        {
            this.FamilyInfo = new HashSet<FamilyInfo>();
        }
    
        public int Id { get; set; }
        public string RealName { get; set; }
        public string EmpCode { get; set; }
        public string Sex { get; set; }
        public string IdCard { get; set; }
        public string Password { get; set; }
        public string BirthDay { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyInfo> FamilyInfo { get; set; }
        public virtual TravelChoice TravelChoice { get; set; }
    }
}
