//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelStage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelStage()
        {
            this.TravelChoice = new HashSet<TravelChoice>();
        }
    
        public int Id { get; set; }
        public string StartDate { get; set; }
        public int Count { get; set; }
        public int Days { get; set; }
        public double Price { get; set; }
        public int TravelCategoryId { get; set; }
    
        public virtual TravelCategory TravelCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelChoice> TravelChoice { get; set; }
    }
}
